"""Add status to Booking

Revision ID: 3d3ba20dfb4e
Revises:
Create Date: 2025-03-19 15:22:01.288306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d3ba20dfb4e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "bookings",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("NOW()"),  # or func.now() in Python code
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("bookings", "updated_at")

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False,
                  nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("user", "admin", name="user_roles"),
            server_default=sa.text("'user'::user_roles"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "bookings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False,
                  nullable=False),
        sa.Column("lodging_id", sa.INTEGER(), autoincrement=False,
                  nullable=False),
        sa.Column(
            "check_in_date", postgresql.TIMESTAMP(), autoincrement=False,
            nullable=False
        ),
        sa.Column(
            "check_out_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False,
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["lodging_id"], ["lodgings.id"], name="bookings_lodging_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="bookings_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="bookings_pkey"),
    )
    op.create_index("ix_bookings_id", "bookings", ["id"], unique=False)
    op.create_table(
        "lodgings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("location", sa.VARCHAR(), autoincrement=False,
                  nullable=False),
        sa.Column(
            "price_per_night",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("availability", sa.BOOLEAN(), autoincrement=False,
                  nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False,
                  nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False,
            nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False,
            nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="lodgings_pkey"),
    )
    op.create_index("ix_lodgings_id", "lodgings", ["id"], unique=False)
    # ### end Alembic commands ###
